name: "Deploy to environment"
description: "Deploys python-greetings application to the environment"
inputs:
  environment:
    description: 'Environment where to execute tests against'
    required: true
  port:
    description: 'Open port for accessing Python application'
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout python-greetings repository
      uses: actions/checkout@v4
      with:
        repository: mtararujs/python-greetings
        path: python-greetings

    - name: Stop existing application
      shell: cmd
      working-directory: python-greetings
      run: pm2 delete greetings-app-${{ inputs.environment}} & EXIT /B 0

    - name: Start application
      shell: cmd
      working-directory: python-greetings
      run: |
          set RUNNER_TRACKING_ID=
          pm2 start app.py --name greetings-app-${{ inputs.environment}} -- --port ${{ inputs.port}}
