name: "Deploy to Dev"
description: "Deploys python-greetings application to the dev environment"
runs:
  using: "composite"
  steps:
    - name: Checkout python-greetings repository
      uses: actions/checkout@v4
      with:
        repository: mtararujs/python-greetings
        path: python-greetings

    - name: Stop existing application
      shell: cmd
      working-directory: python-greetings
      run: pm2 delete greetings-app-dev & EXIT /B 0

    - name: Start application
      shell: cmd
      working-directory: python-greetings
      run: |
          set RUNNER_TRACKING_ID=
          pm2 start app.py --name greetings-app-dev -- --port 7001
