name: Python greetings pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install-pip-deps:
    runs-on: [self-hosted]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/build
          
  deploy-to-dev:
    runs-on: [self-hosted]
    needs: install-pip-deps
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Dev
        uses: ./.github/actions/deploy
        with:
          environment: 'dev'
          port: '7001'
          
  tests-on-dev:
    runs-on: [self-hosted]
    needs: deploy-to-dev
    steps:
      - name: Run Tests on Dev
        uses: ./.github/actions/test
        with:
          environment: 'dev'
          test-suit: 'greetings'
  
  deploy-to-staging:
    runs-on: [self-hosted]
    needs: tests-on-dev
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Dev
        uses: ./.github/actions/deploy
        with:
          environment: 'staging'
          port: '7002'
          
  tests-on-staging:
    runs-on: [self-hosted]
    needs: deploy-to-staging
    steps:
      - name: Run Tests on staging
        uses: ./.github/actions/test
        with:
          environment: 'staging'
          test-suit: 'greetings'

  deploy-to-preprod:
    runs-on: [self-hosted]
    needs: tests-on-staging
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to preprod
        uses: ./.github/actions/deploy
        with:
          environment: 'preprod'
          port: '7003'
          
  tests-on-preprod:
    runs-on: [self-hosted]
    needs: deploy-to-preprod
    steps:
      - name: Run Tests on preprod
        uses: ./.github/actions/test
        with:
          environment: 'preprod'
          test-suit: 'greetings'

  deploy-to-prod:
    runs-on: [self-hosted]
    needs: tests-on-preprod
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to prod
        uses: ./.github/actions/deploy
        with:
          environment: 'prod'
          port: '7004'
          
  tests-on-prod:
    runs-on: [self-hosted]
    needs: deploy-to-prod
    steps:
      - name: Run Tests on prod
        uses: ./.github/actions/test
        with:
          environment: 'prod'
          test-suit: 'greetings'