name: Python greetings pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install-pip-deps:
    runs-on: [self-hosted]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/build
          
  deploy-to-dev:
    runs-on: [self-hosted]
    needs: install-pip-deps
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Dev
        uses: ./.github/actions/deploy
          
  tests-on-dev:
    runs-on: [self-hosted]
    needs: deploy-to-dev
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          clean: false 

      - name: Run Tests on Dev
        uses: ./.github/actions/test